function llg_parameter_gui(cfg)
%LLG_PARAMETER_GUI Edit, run, plot, and save canonical LLGS parameters.
%
% llg_parameter_gui() starts from default_params(). Pass an already
% canonical parameter struct to use different initial values.

if nargin < 1
    cfg = default_params();
else
    validate_params(cfg);
end

catalog = parameter_catalog();
table_data = cell(size(catalog, 1), 3);
for row_idx = 1:size(catalog, 1)
    table_data{row_idx, 1} = catalog{row_idx, 1};
    table_data{row_idx, 2} = value_to_text( ...
        get_catalog_value(cfg, catalog{row_idx, 1}));
    table_data{row_idx, 3} = catalog{row_idx, 2};
end

window = figure('Name', 'LLGS Parameter Editor', ...
    'NumberTitle', 'off', 'MenuBar', 'none', 'ToolBar', 'none', ...
    'Position', [100, 100, 1100, 680], 'Resize', 'on');

parameter_table = uitable(window, 'Data', table_data, ...
    'ColumnName', {'Parameter', 'Value', 'Unit'}, ...
    'ColumnEditable', [false, true, false], ...
    'ColumnWidth', {260, 260, 120}, ...
    'Units', 'normalized', 'Position', [0.02, 0.14, 0.59, 0.83]);

plot_axes = axes('Parent', window, 'Units', 'normalized', ...
    'Position', [0.68, 0.22, 0.29, 0.70]);
title(plot_axes, 'Magnetization');
xlabel(plot_axes, 'time (ns)');
ylabel(plot_axes, 'm');
grid(plot_axes, 'on');

uicontrol(window, 'Style', 'text', 'String', 'Output MAT file:', ...
    'HorizontalAlignment', 'left', 'Units', 'normalized', ...
    'Position', [0.02, 0.075, 0.12, 0.035]);
output_edit = uicontrol(window, 'Style', 'edit', ...
    'String', default_output_file(), 'HorizontalAlignment', 'left', ...
    'Units', 'normalized', 'Position', [0.14, 0.075, 0.35, 0.045]);
uicontrol(window, 'Style', 'pushbutton', 'String', 'Browse...', ...
    'Callback', @browse_output, 'Units', 'normalized', ...
    'Position', [0.50, 0.075, 0.11, 0.045]);

status_text = uicontrol(window, 'Style', 'text', 'String', 'Ready', ...
    'HorizontalAlignment', 'left', 'Units', 'normalized', ...
    'Position', [0.02, 0.015, 0.59, 0.04]);
uicontrol(window, 'Style', 'pushbutton', 'String', 'Run and Save', ...
    'FontWeight', 'bold', 'Callback', @run_simulation, ...
    'Units', 'normalized', 'Position', [0.76, 0.07, 0.15, 0.07]);

    function browse_output(~, ~)
        [file_name, folder] = uiputfile('*.mat', ...
            'Save LLGS result', get(output_edit, 'String'));
        if ~isequal(file_name, 0)
            set(output_edit, 'String', fullfile(folder, file_name));
        end
    end

    function run_simulation(~, ~)
        try
            set(status_text, 'String', 'Validating parameters...');
            drawnow;
            used_cfg = table_to_config(get(parameter_table, 'Data'), ...
                cfg, catalog);
            output_file = get(output_edit, 'String');
            set(status_text, 'String', 'Running solver...');
            drawnow;
            result = run_llg_and_save(used_cfg, output_file);

            if used_cfg.output.plot
                plot(plot_axes, result.tt * 1e9, result.mmx, ...
                    result.tt * 1e9, result.mmy, ...
                    result.tt * 1e9, result.mmz, ...
                    'LineWidth', used_cfg.output.line_width);
                xlabel(plot_axes, 'time (ns)');
                ylabel(plot_axes, 'm');
                legend(plot_axes, 'm_x', 'm_y', 'm_z', ...
                    'Location', 'best');
                grid(plot_axes, 'on');
            else
                cla(plot_axes);
                title(plot_axes, 'Plot disabled by output.plot');
            end
            set(status_text, 'String', ['Saved: ' output_file]);
        catch exception
            set(status_text, 'String', ['Error: ' exception.message]);
            errordlg(exception.message, 'LLGS run failed', 'modal');
        end
    end
end

function cfg = table_to_config(table_data, cfg, catalog)
init_theta_deg = [];
init_phi_deg = [];
for row_idx = 1:size(catalog, 1)
    path = catalog{row_idx, 1};
    template = get_catalog_value(cfg, path);
    value = text_to_value(table_data{row_idx, 2}, template, path);
    if strcmp(path, 'initial.theta_deg')
        init_theta_deg = value;
    elseif strcmp(path, 'initial.phi_deg')
        init_phi_deg = value;
    else
        cfg = set_nested_value(cfg, path, value);
    end
end
init_theta = init_theta_deg / 180 * pi;
init_phi = init_phi_deg / 180 * pi;
cfg.initial.magnetization = [sin(init_theta) * cos(init_phi), ...
    sin(init_theta) * sin(init_phi), cos(init_theta)];
validate_params(cfg);
end

function value = text_to_value(text_value, template, path)
if ischar(template)
    if ~ischar(text_value)
        error('LLGSGUI:InvalidTextValue', ...
            'Parameter "%s" must be text.', path);
    end
    value = strtrim(text_value);
    return;
end

if isnumeric(text_value)
    text_value = num2str(text_value, 17);
end
if ~ischar(text_value)
    error('LLGSGUI:InvalidNumericValue', ...
        'Parameter "%s" must be numeric.', path);
end

tokens = regexp(text_value, ...
    '[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?|[-+]?Inf|NaN', ...
    'match');
numbers = str2double(tokens);
if numel(numbers) ~= numel(template)
    error('LLGSGUI:WrongElementCount', ...
        'Parameter "%s" requires %d numeric value(s).', ...
        path, numel(template));
end

if isscalar(template)
    value = numbers;
elseif isvector(template)
    value = reshape(numbers, size(template));
else
    value = reshape(numbers, size(template, 2), size(template, 1))';
end
end

function text_value = value_to_text(value)
if ischar(value)
    text_value = value;
else
    text_value = mat2str(value, 17);
end
end

function value = get_nested_value(cfg, path)
parts = strsplit(path, '.');
value = cfg;
for idx = 1:numel(parts)
    value = value.(parts{idx});
end
end

function value = get_catalog_value(cfg, path)
if strcmp(path, 'initial.theta_deg')
    value = acos(max(-1, min(1, cfg.initial.magnetization(3)))) ...
        / pi * 180;
elseif strcmp(path, 'initial.phi_deg')
    value = atan2(cfg.initial.magnetization(2), ...
        cfg.initial.magnetization(1)) / pi * 180;
else
    value = get_nested_value(cfg, path);
end
end

function cfg = set_nested_value(cfg, path, value)
parts = strsplit(path, '.');
if numel(parts) == 2
    cfg.(parts{1}).(parts{2}) = value;
elseif numel(parts) == 3
    cfg.(parts{1}).(parts{2}).(parts{3}) = value;
else
    error('LLGSGUI:UnsupportedParameterPath', ...
        'Unsupported parameter path "%s".', path);
end
end

function output_file = default_output_file()
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
output_file = fullfile(pwd, ['llg_output_' timestamp '.mat']);
end

function catalog = parameter_catalog()
% The unit labels mirror the central conventions in README.md.
catalog = { ...
    'material.Ms', 'emu/cm^3'; ...
    'material.damping', 'dimensionless'; ...
    'geometry.LFL', 'm'; ...
    'geometry.WFL', 'm'; ...
    'geometry.tFL', 'm'; ...
    'geometry.LHM', 'm'; ...
    'geometry.WHM', 'm'; ...
    'geometry.tHM', 'm'; ...
    'solver.runtime', 's'; ...
    'solver.tstep', 's'; ...
    'solver.method', 'selection'; ...
    'solver.dimensionless', '0 or 1'; ...
    'solver.g', 'dimensionless'; ...
    'fields.anisotropy_mode', '1 = IMA, 2 = PMA'; ...
    'fields.Hk', 'T'; ...
    'fields.external', 'T'; ...
    'fields.demag_tensor', 'dimensionless'; ...
    'fields.dipole_enabled', '0 or 1'; ...
    'fields.dipole_tensor', 'dimensionless'; ...
    'torques.stt.damping_like_enabled', '0 or 1'; ...
    'torques.stt.field_like_enabled', '0 or 1'; ...
    'torques.stt.current_density', 'A/m^2'; ...
    'torques.stt.free_layer_polarization', 'dimensionless'; ...
    'torques.stt.polarization', 'dimensionless'; ...
    'torques.stt.pinned_magnetization', 'dimensionless'; ...
    'torques.stt.field_like_ratio', 'dimensionless'; ...
    'torques.sot.damping_like_enabled', '0 or 1'; ...
    'torques.sot.field_like_enabled', '0 or 1'; ...
    'torques.sot.current_density', 'A/m^2'; ...
    'torques.sot.spin_hall_angle', 'dimensionless'; ...
    'torques.sot.spin_diffusion_length', 'm'; ...
    'torques.sot.polarization', 'dimensionless'; ...
    'torques.sot.field_like_ratio', 'dimensionless'; ...
    'thermal.enabled', '0 or 1'; ...
    'thermal.temperature', 'K'; ...
    'initial.theta_deg', 'degrees from +z'; ...
    'initial.phi_deg', 'degrees from +x'; ...
    'output.plot', '0 or 1'; ...
    'output.line_width', 'points'};
end
