function config = make_config(overrides)
%MAKE_CONFIG Return LLGS feature flags as an explicit configuration struct.

config = struct( ...
    'IMAPMA', 2, ...
    'SOT_DLT', 0, ...
    'SOT_FLT', 0, ...
    'STT_DLT', 1, ...
    'STT_FLT', 0, ...
    'dipolee', 0, ...
    'thermalnois', 0, ...
    'dimensionlessLLG', 0);

if nargin < 1 || isempty(overrides)
    return;
end

override_names = fieldnames(overrides);
for idx = 1:numel(override_names)
    name = override_names{idx};
    if ~isfield(config, name)
        error('make_config:UnknownField', ...
            'Unknown configuration field "%s".', name);
    end
    config.(name) = overrides.(name);
end
end
